"""add fundamental fields

Revision ID: 924198b562f1
Revises: 2f0763747cdf
Create Date: 2025-11-19 05:40:00.169827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '924198b562f1'
down_revision = '2f0763747cdf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('target_value', sa.String(length=100), nullable=True),
    sa.Column('current_value', sa.String(length=100), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_goal_status', 'health_goals', ['status'], unique=False)
    op.create_index('idx_goal_user_id', 'health_goals', ['user_id'], unique=False)
    op.create_index('idx_goal_user_status', 'health_goals', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_health_goals_id'), 'health_goals', ['id'], unique=False)
    op.create_index(op.f('ix_health_goals_user_id'), 'health_goals', ['user_id'], unique=False)
    op.create_table('nutrition_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=50), nullable=True),
    sa.Column('meal_description', sa.String(length=500), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein_grams', sa.Float(), nullable=True),
    sa.Column('carbs_grams', sa.Float(), nullable=True),
    sa.Column('fat_grams', sa.Float(), nullable=True),
    sa.Column('water_intake_ml', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('logged_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nutrition_logged_at', 'nutrition_logs', ['logged_at'], unique=False)
    op.create_index('idx_nutrition_user_id', 'nutrition_logs', ['user_id'], unique=False)
    op.create_index('idx_nutrition_user_logged', 'nutrition_logs', ['user_id', 'logged_at'], unique=False)
    op.create_index(op.f('ix_nutrition_logs_id'), 'nutrition_logs', ['id'], unique=False)
    op.create_index(op.f('ix_nutrition_logs_user_id'), 'nutrition_logs', ['user_id'], unique=False)
    op.add_column('health_insights', sa.Column('reasoning', sa.Text(), nullable=True))
    op.add_column('health_insights', sa.Column('rank', sa.Integer(), nullable=True))
    op.add_column('health_insights', sa.Column('related_metric_type', sa.String(length=50), nullable=True))
    op.create_index('idx_insight_created_at', 'health_insights', ['created_at'], unique=False)
    op.create_index('idx_insight_rank', 'health_insights', ['rank'], unique=False)
    op.create_index('idx_insight_user_id', 'health_insights', ['user_id'], unique=False)
    op.create_index('idx_insight_user_rank', 'health_insights', ['user_id', 'rank'], unique=False)
    op.create_foreign_key(None, 'health_insights', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('health_metrics', sa.Column('intensity', sa.String(length=20), nullable=True))
    op.add_column('health_metrics', sa.Column('duration', sa.Integer(), nullable=True))
    op.create_index('idx_metric_recorded_at', 'health_metrics', ['recorded_at'], unique=False)
    op.create_index('idx_metric_type', 'health_metrics', ['metric_type'], unique=False)
    op.create_index('idx_metric_user_id', 'health_metrics', ['user_id'], unique=False)
    op.create_index('idx_metric_user_type_recorded', 'health_metrics', ['user_id', 'metric_type', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_health_metrics_metric_type'), 'health_metrics', ['metric_type'], unique=False)
    op.create_index(op.f('ix_health_metrics_recorded_at'), 'health_metrics', ['recorded_at'], unique=False)
    op.create_foreign_key(None, 'health_metrics', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('marital_status', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('occupation', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('medical_history', sa.Text(), nullable=True))
    op.create_index('idx_user_created_at', 'users', ['created_at'], unique=False)
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_username', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_index('idx_user_created_at', table_name='users')
    op.drop_column('users', 'medical_history')
    op.drop_column('users', 'occupation')
    op.drop_column('users', 'marital_status')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'date_of_birth')
    op.drop_constraint(None, 'health_metrics', type_='foreignkey')
    op.drop_index(op.f('ix_health_metrics_recorded_at'), table_name='health_metrics')
    op.drop_index(op.f('ix_health_metrics_metric_type'), table_name='health_metrics')
    op.drop_index('idx_metric_user_type_recorded', table_name='health_metrics')
    op.drop_index('idx_metric_user_id', table_name='health_metrics')
    op.drop_index('idx_metric_type', table_name='health_metrics')
    op.drop_index('idx_metric_recorded_at', table_name='health_metrics')
    op.drop_column('health_metrics', 'duration')
    op.drop_column('health_metrics', 'intensity')
    op.drop_constraint(None, 'health_insights', type_='foreignkey')
    op.drop_index('idx_insight_user_rank', table_name='health_insights')
    op.drop_index('idx_insight_user_id', table_name='health_insights')
    op.drop_index('idx_insight_rank', table_name='health_insights')
    op.drop_index('idx_insight_created_at', table_name='health_insights')
    op.drop_column('health_insights', 'related_metric_type')
    op.drop_column('health_insights', 'rank')
    op.drop_column('health_insights', 'reasoning')
    op.drop_index(op.f('ix_nutrition_logs_user_id'), table_name='nutrition_logs')
    op.drop_index(op.f('ix_nutrition_logs_id'), table_name='nutrition_logs')
    op.drop_index('idx_nutrition_user_logged', table_name='nutrition_logs')
    op.drop_index('idx_nutrition_user_id', table_name='nutrition_logs')
    op.drop_index('idx_nutrition_logged_at', table_name='nutrition_logs')
    op.drop_table('nutrition_logs')
    op.drop_index(op.f('ix_health_goals_user_id'), table_name='health_goals')
    op.drop_index(op.f('ix_health_goals_id'), table_name='health_goals')
    op.drop_index('idx_goal_user_status', table_name='health_goals')
    op.drop_index('idx_goal_user_id', table_name='health_goals')
    op.drop_index('idx_goal_status', table_name='health_goals')
    op.drop_table('health_goals')
    # ### end Alembic commands ###
